### ISSUE TITLE
add: ds.toml support

### ISSUE THREAD

**Issue by metaist** [metaist/ds#2]
A very simple native format roughly inspired by the [`scripts`][1] field in `package.json` and the [`composite`][2] type in `pdm`.

```toml
# ds.toml
[scripts]
build = "cmd"
clean = "rm -rf build"
all = ["clean", "build"]
```

- [x] find the nearest `ds.toml`
- [x] `scripts` subkeys are the names of commands
- [x] string values are just the shell command to run
- [x] array values are the names of other script names to run

[1]: https://docs.npmjs.com/cli/v10/using-npm/scripts
[2]: https://pdm-project.org/latest/usage/scripts/#composite
