### ISSUE TITLE
add: composite task arguments

### ISSUE THREAD

**Issue by metaist** [metaist/ds#20]
When I tried this, part of the problem was loops.

```toml
[scripts]
"ruff:check" = "ruff check ."
ruff = ["ruff:check --fix"] # I want this to end up calling $ ruff check . --fix
```
The problem is that I was doing the arguments even for simple string versions. A possible solution is to mark tasks as being part of a composite (or I can infer that those tasks that don't have a name are part of a composite).
