### ISSUE TITLE
add: argument interpolation

### ISSUE THREAD

**Issue by metaist** [metaist/ds#21]
There are two places we could think about doing this:

1. Command-line arguments being passed to tasks (see #4).
2. Tasks passing additional arguments to subtasks (see #20).

```toml
[scripts]
ls = "ls" # == "ls $@"
ls_dir = "ls $1 -lah $@"
```
