### ISSUE TITLE
fix: `shell` and `cmd` error suppression

### ISSUE THREAD

**Issue by metaist** [metaist/ds#25]
Currently:
```toml
[scripts]
task-1 = {"shell": "-exit 1"}
task-2 = {"cmd": ["-exit", "1"]}
```
Neither of these properly suppresses the error because we don't pass the strings back to `Task.parse`.
