### ISSUE TITLE
fix: running same task twice

### ISSUE THREAD

**Issue by metaist** [metaist/ds#29]
While I was figuring out #21, I ended up adding in logic to prevent circularity. However, this also prevents the same task from running twice. But, ironically, having #21 done meant that it is easy to define a task with an argument and then have other tasks call it with different arguments.

```toml
[scripts]
build = "touch build/$1"
clean = "rm -rf build"
all = ["clean", "-mkdir build", "build foo", "build bar", "echo 'Done'"]
```
- Currently: runs `clean`, `mkdir build`, `build foo`, `echo 'Done'` (skips `build bar`)
- Expected: all of the steps run

**Comment by metaist** [comment]
Here's my analysis:
```
build => |touch
clean => |rm
all => clean => |mkdir => build => build => |echo
```
So is the problem when a `composite` task is called multiple times?

**Comment by metaist** [comment]
Only composite tasks can call other tasks. So the concern is that in the call chain you somehow end up calling yourself again.

Here's the simplest loop:
```toml
loop = ["loop"]
```

If a `composite` task cannot be called twice, we prevent this loop.

**Comment by metaist** [comment]
Here's a more complicated loop:

```toml
[scripts]
a = ["b"]
b = ["a"]
# a=> b => a => b...
```
Ok, so far so good.

**Comment by metaist** [comment]
What about a more real-world use case:
```toml
[scripts]
clean = ["rm -rf build", "rm build-artifacts"]
build = "touch build/$1"
run = ["clean", "build foo", "mv foo new-location", "clean"]
```
In this case, `clean` is a `composite` task, but we're calling it twice at the same level-- it's not cycling back to `run`.
