### ISSUE TITLE
handle: duplicate task names

### ISSUE THREAD

**Issue by metaist** [metaist/ds#9]
We need some way of handling ambiguous / duplicate task names. When we implement #8 we run the risk of having the same name in multiple sections.

```toml
[tool.ds.scripts]
a = "echo 'ds:a'"
b = "echo 'ds:b'"

[tool.pdm.scripts]
a = "echo 'pdm:a'"
c = "echo 'pdm:c'"
```

What should the result be?
